name: Build & Deploy to Cloud Run (GCP)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker for Google Artifact Registry
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build Docker image for AMD64
      run: |
        docker buildx build \
          --platform linux/amd64 \
          -f dockerfiles/predict_model.dockerfile \
          -t sudoku-solver-amd64 \
          --load \
          .

    - name: Tag Docker image for Artifact Registry
      run: |
        docker tag sudoku-solver-amd64 \
          europe-west1-docker.pkg.dev/dvc-drive-460320/sudoku-repo/sudoku-solver

    - name: Push Docker image to Artifact Registry
      run: |
        docker push europe-west1-docker.pkg.dev/dvc-drive-460320/sudoku-repo/sudoku-solver

# Deployment to Cloud Run has been commented out intentionally.
# We have **stopped the instance after successful deployment** to GCP,
# so this part is not required for CI workflow to pass.
# Uncomment and use if re-deployment is needed in the future.

# - name: Deploy to Cloud Run
#   run: |
#     gcloud run deploy sudoku-solver \
#       --image=europe-west1-docker.pkg.dev/dvc-drive-460320/sudoku-repo/sudoku-solver \
#       --platform=managed \
#       --region=europe-west1 \
#       --allow-unauthenticated \
#       --memory=1Gi \
#       --timeout=1000 \
#       --max-instances=1
